import { useMemo, useState } from 'react'
import { Section } from '../components/Section'
import { certificateCategories, certificates, type Certificate, type CertificateCategory } from '../data/certificates'

function CertificateModal({ certificate, onClose }: { certificate: Certificate; onClose: () => void }) {
  return <div className="certificate-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><div className="certificate-dialog panel" role="dialog" aria-modal="true" aria-labelledby="certificate-dialog-title"><button className="dialog-close" type="button" aria-label="Close certificate details" onClick={onClose}>×</button>{certificate.image ? <img className="certificate-image" src={certificate.image} alt={`${certificate.title} certificate`} loading="lazy" /> : <div className="certificate-placeholder"><span aria-hidden="true">◇</span><strong>Certificate Preview Unavailable</strong><span>{certificate.issuer}</span></div>}<div className="certificate-dialog-copy"><p className="project-category">{certificate.category}</p><h3 id="certificate-dialog-title">{certificate.title}</h3><p>{certificate.issuer}</p>{certificate.issueDate && <p>Issued {certificate.issueDate}</p>}{certificate.credentialId && <p>Credential ID: {certificate.credentialId}</p>}{certificate.credentialUrl && <a className="button button-small" href={certificate.credentialUrl} target="_blank" rel="noreferrer">Verify Credential ↗</a>}</div></div></div>
}

export function Certificates() {
  const [category, setCategory] = useState<CertificateCategory>('All')
  const [search, setSearch] = useState('')
  const [selected, setSelected] = useState<Certificate | null>(null)
  const visible = useMemo(() => certificates.filter((certificate) => {
    const matchesCategory = category === 'All' || certificate.category === category
    const haystack = [certificate.title, certificate.issuer, certificate.category, certificate.credentialId ?? ''].join(' ').toLowerCase()
    return matchesCategory && (!search.trim() || haystack.includes(search.trim().toLowerCase()))
  }), [category, search])

  return <><Section id="certificates" eyebrow="06 / Credentials" title="Certifications & Credentials" description="Completed learning credentials and certifications relevant to cybersecurity, networking, programming, and technical development."><div className="certificate-controls"><div className="project-filters" role="group" aria-label="Filter certificates by category">{certificateCategories.map((item) => <button className={`filter-chip ${category === item ? 'is-selected' : ''}`} type="button" aria-pressed={category === item} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div><label className="project-search"><span className="sr-only">Search certificates</span><span aria-hidden="true">⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search certificates..." /></label></div>{visible.length ? <div className="certificate-grid">{visible.map((certificate) => <article className="certificate-card panel" key={certificate.id}><div className="certificate-card-preview">{certificate.image ? <img src={certificate.image} alt="" loading="lazy" /> : <span aria-hidden="true">◇</span>}</div><div className="certificate-card-copy"><p className="project-category">{certificate.category}</p><h3>{certificate.title}</h3><p>{certificate.issuer}</p>{certificate.issueDate && <span className="certificate-date">{certificate.issueDate}</span>}<button className="text-button" type="button" onClick={() => setSelected(certificate)}>View credential <span aria-hidden="true">↗</span></button></div></article>)}</div> : <div className="empty-state panel"><span className="empty-icon">◇</span><h3>{search ? 'No certificates match your search.' : 'Credentials will appear here when verified.'}</h3><p>{search ? 'Try another term or reset the filters.' : 'No certificate records have been added to the portfolio data yet.'}</p>{search && <button className="button button-small" type="button" onClick={() => { setSearch(''); setCategory('All') }}>Reset filters</button>}</div>}</Section>{selected && <CertificateModal certificate={selected} onClose={() => setSelected(null)} />}</>
}
